/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as TriathlonRouteImport } from './routes/triathlon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const TriathlonRoute = TriathlonRouteImport.update({
  id: '/triathlon',
  path: '/triathlon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movement': typeof MovementRoute
  '/triathlon': typeof TriathlonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movement': typeof MovementRoute
  '/triathlon': typeof TriathlonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movement': typeof MovementRoute
  '/triathlon': typeof TriathlonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movement' | '/triathlon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movement' | '/triathlon'
  id: '__root__' | '/' | '/movement' | '/triathlon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementRoute: typeof MovementRoute
  TriathlonRoute: typeof TriathlonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triathlon': {
      id: '/triathlon'
      path: '/triathlon'
      fullPath: '/triathlon'
      preLoaderRoute: typeof TriathlonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementRoute: MovementRoute,
  TriathlonRoute: TriathlonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
